language: r
r: bioc-release
bioc_check: true

r_packages:
  - covr
  
before_script:
  # ensure bioc-devel is being used
  - R -e 'BiocManager::install(version = "3.12", ask=FALSE)'
  - R -e 'BiocManager::install("BiocStyle")'
  - R -e 'BiocManager::install("TPP")'
  - R -e 'BiocManager::valid()'
  
after_success:
  - Rscript -e 'covr::codecov()'
